services:
  postgres-bankapp:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER:  "postgres"
      POSTGRES_DB: "bank"
    ports:
      - "5432:5432"
    volumes:
      - "pgbankdata:/var/lib/postgresql/data"
    networks:
      - "bankappbackend"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis-bankapp:
    image: redis:8.2.0-alpine
    ports:
      - "6379:6379"
    networks:
      - "bankappbackend"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  simplebank:
    build:
      context: .
      dockerfile: Dockerfile 
      target: dev
    ports:
      - "3000:9090"
    networks:
      - bankappbackend
    volumes:
      - ./:/app
    depends_on:
      postgres-bankapp:
        condition: service_healthy
      redis-bankapp:
        condition: service_healthy
  simplebankprod:
    build:
      context: .
      dockerfile: Dockerfile 
      target: runtime
    ports:
      - "9090:9090"
    networks:
      - bankappbackend
    secrets:
      - db_password
    volumes:
      - pgbankdata:/var/lib/postgresql/data
    depends_on:
      postgres-bankapp:
        condition: service_healthy
      redis-bankapp:
        condition: service_healthy

volumes:
  pgbankdata:
    driver: "local"
 
networks:
  bankappbackend:

secrets:
  db_password:
    file: /home/leo/workspace/secrets/db_password.txt
 