name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    env: 
      DSN: ${{ secrets.DSN }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: postgres
          POSTGRES_DB: bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/
          which migrate

      - name: Build
        run: make build

      - name: Run migrations
        env:
          DSN: postgresql://postgres:secret@localhost:5432/bank?sslmode=disable
        run: make db/migrations/up

      - name: Write app.env for CI
        run: echo "DSN=postgresql://postgres:secret@localhost:5432/bank?sslmode=disable" > app.env

      - name: Test
        run: make test
